set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim

" tell vim to yank to system clipboard
set clipboard=unnamed
" enable syntax highlighting
syntax on

call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

call vundle#end()   

filetype plugin indent on
